
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TANVEER UL HAQ
 */
public class Employee_Payment extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Connection conn=null;
     
    public Employee_Payment() {
        initComponents();
        
        try{
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@"+"DESKTOP-32DHV0C"+ ":" +"1521"+":", "system", "123");
            System.out.println("Connection established"); 
        }
        catch(Exception e)
        {
            System.out.println("Error occurs");
        }
        
        try{
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("Select * from employee_payment order by ID_No ASC");
         
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         }  
            catch(Exception e)
                    {
                    System.out.println("   Error");
                    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manage_room = new javax.swing.JButton();
        New_student = new javax.swing.JButton();
        update_student = new javax.swing.JButton();
        student_fee = new javax.swing.JButton();
        living_student = new javax.swing.JButton();
        leaved_student = new javax.swing.JButton();
        new_employee = new javax.swing.JButton();
        update_employee = new javax.swing.JButton();
        employee_payment = new javax.swing.JButton();
        working_employee = new javax.swing.JButton();
        Leaved_employee = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        Dashboard = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 25));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hostel Management System");

        manage_room.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manage_room.setText("Manage rooms");
        manage_room.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manage_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_roomActionPerformed(evt);
            }
        });

        New_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        New_student.setText("New Student");
        New_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        New_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_studentActionPerformed(evt);
            }
        });

        update_student.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_student.setText("Update and delete Student");
        update_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studentActionPerformed(evt);
            }
        });

        student_fee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        student_fee.setText("Student Fee");
        student_fee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        student_fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_feeActionPerformed(evt);
            }
        });

        living_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        living_student.setText("Living Students");
        living_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        living_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                living_studentActionPerformed(evt);
            }
        });

        leaved_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leaved_student.setText("Leaved Student");
        leaved_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaved_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaved_studentActionPerformed(evt);
            }
        });

        new_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_employee.setText("New Employee");
        new_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        new_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_employeeActionPerformed(evt);
            }
        });

        update_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_employee.setText("Update and delete Employee");
        update_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_employeeActionPerformed(evt);
            }
        });

        employee_payment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employee_payment.setText("Employee Payment");
        employee_payment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        working_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        working_employee.setText("Working Employees");
        working_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        working_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                working_employeeActionPerformed(evt);
            }
        });

        Leaved_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leaved_employee.setText("Leaved Employee");
        Leaved_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Leaved_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leaved_employeeActionPerformed(evt);
            }
        });

        log_out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log_out.setText("Log Out");
        log_out.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Employee Payment Form");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("E-mail ID");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CNIC Number");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Month");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Dues / Amount");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Designation");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "............Select............", "Hostel Incharge", "Cleaning Staff", "Mess Staff", "Accounts Manager" }));

        Dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manage_room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(New_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(living_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaved_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(new_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employee_payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(working_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Leaved_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(312, 312, 312)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(67, 67, 67)
                                        .addComponent(jTextField5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(119, 119, 119)
                                        .addComponent(jTextField2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(151, 151, 151)
                                        .addComponent(jTextField1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160)
                        .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manage_room, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(New_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(living_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leaved_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employee_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(working_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Leaved_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        Login Li = new Login();
        Li.show();
        this.hide();
    }//GEN-LAST:event_log_outActionPerformed

    private void manage_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_roomActionPerformed
        // TODO add your handling code here:
       new Manage_Room().setVisible(true);
          this.hide();
    }//GEN-LAST:event_manage_roomActionPerformed

    private void New_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_studentActionPerformed
        // TODO add your handling code here:
         new New_Students().setVisible(true);
        
        this.hide();
      
    }//GEN-LAST:event_New_studentActionPerformed

    private void update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studentActionPerformed
        // TODO add your handling code here:
           new Update_and_delete_students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_update_studentActionPerformed

    private void student_feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_feeActionPerformed
        // TODO add your handling code here:
         new Student_fee().setVisible(true);
        this.hide();
    }//GEN-LAST:event_student_feeActionPerformed

    private void leaved_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaved_studentActionPerformed
        // TODO add your handling code here:
        new Leaved_Students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_leaved_studentActionPerformed

    private void new_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_employeeActionPerformed
        // TODO add your handling code here:
        new New_Employee().setVisible(true);
        this.hide();
    }//GEN-LAST:event_new_employeeActionPerformed

    private void update_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_employeeActionPerformed
        // TODO add your handling code here:
         new Update_and_delete_Employee().setVisible(true);
        this.hide();
    }//GEN-LAST:event_update_employeeActionPerformed

    private void working_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_working_employeeActionPerformed
        // TODO add your handling code here:
         new Working_Employees().setVisible(true);
        this.hide();
    }//GEN-LAST:event_working_employeeActionPerformed

    private void Leaved_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leaved_employeeActionPerformed
        // TODO add your handling code here:
         new Leaved_Employees().setVisible(true);
        this.hide();
    }//GEN-LAST:event_Leaved_employeeActionPerformed

    private void living_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_living_studentActionPerformed
        // TODO add your handling code here:
        new Living_Students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_living_studentActionPerformed

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
         new Dashboard().setVisible(true);
        this.hide();
    }//GEN-LAST:event_DashboardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String tf = jTextField3.getText();
    //    String Designation = jComboBox2.getSelectedItem().toString();
    if(jTextField3.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(this,"Search field is empty \n Kindly give input");
        }
        else
        try{
            ResultSet rs=conn.createStatement().executeQuery("Select * from new_employee where ID_No like '%"+tf+"%' ");// and designation='"+Designation+"'");
            ResultSet emp=conn.createStatement().executeQuery("Select * from new_employee where ID_No like '%"+tf+"%' and working='Yes'");
            ResultSet r=conn.createStatement().executeQuery("Select * from employee_payment where ID_No='"+tf+"' order by month DESC");
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            
            if(emp.next())
            {
                if(rs.next())
            {
                String name = rs.getString("name");
                jTextField1.setText(name);
                String email = rs.getString("Email_id");
                jTextField2.setText(email);
                String CNIC = rs.getString("Id_No");
                jTextField3.setText(CNIC);
                String Designation =rs.getString("Designation");
                jComboBox2.setSelectedItem(Designation);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"No data Exists","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jComboBox2.setSelectedIndex(0);
                jTextField5.setText("");
                jDateChooser1.setDate(null);
               // jDateChooser2.setDate();
            }
            
            }
            else
            {
                JOptionPane.showMessageDialog(this,"This Employee is not working in hostel at this time.","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jComboBox2.setSelectedIndex(0);
                jTextField5.setText("");
                jDateChooser1.setDate(null);
            
            }
        }
        catch(Exception e)
        {
            System.out.println("   Error");

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String CNIC = jTextField3.getText();
        String amount = jTextField5.getText();
        String designation = jComboBox2.getSelectedItem().toString();
      //  Date month = jDateChooser2.getDate();
    //    int dat;
    //    Calendar cal = Calendar.getInstance();
    //    dat =cal.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        String date = sdf.format(jDateChooser1.getDate());
     //   System.out.println(date);

        SimpleDateFormat sd = new SimpleDateFormat("MMM-yyyy");
        String check_date = sd.format(jDateChooser1.getDate());
        
      //  t1.setDate(date);
       // System.out.println(date);

        try{
            ResultSet r =conn.createStatement().executeQuery("Select * from employee_payment where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
        /*    ResultSet s =conn.createStatement().executeQuery("Select count(*) from employee_payment where ID_No="+CNIC+";");
            String count = s.getString("count(*)");
            for (int i = 0; i < count.length(); i++) {
                String fee_date = r.getString("month");
                System.out.println(fee_date);
            }*/
            if(r.next())
            {
              JOptionPane.showMessageDialog(this,"'"+CNIC+"' already paid payment/salary of this month.","",JOptionPane.PLAIN_MESSAGE);
            }
            else
            {
            conn.createStatement().executeQuery("insert into employee_payment(ID_No, designation, month, amount) values('"+CNIC+"','"+designation+"','"+date+"','"+amount+"')");
            JOptionPane.showMessageDialog(this,"Salary/payment Paid Successfully","",JOptionPane.PLAIN_MESSAGE);
            ResultSet rs=conn.createStatement().executeQuery("Select * from employee_payment order by ID_No ASC");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }    
            
        }
        catch(Exception e)
        {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField5.setText("");
                jDateChooser1.setDate(null);
                jComboBox2.setSelectedIndex(0);
                
                try{
            Statement st=conn.createStatement();
        //    conn.createStatement().executeQuery("delete from employee_payment");
        //    conn.createStatement().executeQuery("delete from new_student");
        //    conn.createStatement().executeQuery("delete from new_employee");
            
            ResultSet rs=st.executeQuery("Select * from employee_payment order by ID_No ASC");
               
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         }  
            catch(Exception e)
                    {
                    System.out.println("   Error");
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         String CNIC = jTextField3.getText();
     
        SimpleDateFormat sdf = new SimpleDateFormat("MMM-yyyy");
        String check_date = sdf.format(jDateChooser1.getDate());
        
        try{
            ResultSet r =conn.createStatement().executeQuery("Select * from employee_payment where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
        
            if(r.next())
            {
           int response= JOptionPane.showConfirmDialog(this, "Are you sure You want to delete Salary/Payment record?", "Confirm",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.YES_OPTION)
            {
                 try{ 
               conn.createStatement().executeQuery("delete from employee_payment where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
               JOptionPane.showMessageDialog(this,"Salary/Payment data deleted","",JOptionPane.PLAIN_MESSAGE);
            }
            catch(Exception e)
            {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
            }
            }}
            else
            {
            JOptionPane.showMessageDialog(this,"No data Exists","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField5.setText("");
                jDateChooser1.setDate(null);
                jComboBox2.setSelectedIndex(0);
            ResultSet rs=conn.createStatement().executeQuery("Select * from employee_payment order by ID_No ASC");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }    
            
        }
        catch(Exception e)
        {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Leaved_employee;
    private javax.swing.JButton New_student;
    private javax.swing.JButton employee_payment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton leaved_student;
    private javax.swing.JButton living_student;
    private javax.swing.JButton log_out;
    private javax.swing.JButton manage_room;
    private javax.swing.JButton new_employee;
    private javax.swing.JButton student_fee;
    private javax.swing.JButton update_employee;
    private javax.swing.JButton update_student;
    private javax.swing.JButton working_employee;
    // End of variables declaration//GEN-END:variables
}
