
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TANVEER UL HAQ
 */
public class Student_fee extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
        Connection conn=null;  
    
    public Student_fee() {
        initComponents();
        
        try{
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@"+"DESKTOP-32DHV0C"+ ":" +"1521"+":", "system", "123");
            System.out.println("Connection established"); 
        }
        catch(Exception e)
        {
            System.out.println("Error occurs");
        }
        
         try{
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("Select * from fees order by ID_No ASC");
         
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         }  
            catch(Exception e)
                    {
                    System.out.println("   Error");
                    }
       
        /*
        try{         
                    Statement st=conn.createStatement();
                //    ResultSet rs=st.executeQuery("SELECT TO_CHAR(SYSDATE, 'MON DD,YYYY') FROM dual;");
                conn.createStatement().executeQuery("insert into table_for_date(id,system_date)values(id_seq.NEXTVAL,sysdate)");
                      ResultSet rs=st.executeQuery("Select * from table_for_date where id=1;");
                //    SimpleDateFormat date = new SimpleDateFormat("DD-MMM-YYYY");
                //    Date dateValue = date.parse(rs.getstring(1));
                 //   String date_value = rs.getString(1);
                  //    Date date = new SimpleDateFormat("DD-MMM-YYYY").parse((String)rs.getValueAt(1,1));
                  //  Calendar cal = Calendar.getInstance();
                  //  cal.setTime(date); 
                    Date cal = rs.getDate("system_date");
                    jDateChooser2.setDate(cal);
                  //  jDateChooser2.setDate(date);
                  //  JDateChooser2.setString()
           }
        catch(Exception e)
        {
            System.out.println("   Error");
        }
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manage_room = new javax.swing.JButton();
        New_student = new javax.swing.JButton();
        update_student = new javax.swing.JButton();
        student_fee = new javax.swing.JButton();
        living_student = new javax.swing.JButton();
        leaved_student = new javax.swing.JButton();
        new_employee = new javax.swing.JButton();
        update_employee = new javax.swing.JButton();
        employee_payment = new javax.swing.JButton();
        working_employee = new javax.swing.JButton();
        Leaved_employee = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 25));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hostel Management System");

        manage_room.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manage_room.setText("Manage rooms");
        manage_room.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manage_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_roomActionPerformed(evt);
            }
        });

        New_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        New_student.setText("New Student");
        New_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        New_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_studentActionPerformed(evt);
            }
        });

        update_student.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_student.setText("Update and delete Student");
        update_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studentActionPerformed(evt);
            }
        });

        student_fee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        student_fee.setText("Student Fee");
        student_fee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        student_fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_feeActionPerformed(evt);
            }
        });

        living_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        living_student.setText("Living Students");
        living_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        living_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                living_studentActionPerformed(evt);
            }
        });

        leaved_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leaved_student.setText("Leaved Student");
        leaved_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaved_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaved_studentActionPerformed(evt);
            }
        });

        new_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_employee.setText("New Employee");
        new_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        new_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_employeeActionPerformed(evt);
            }
        });

        update_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_employee.setText("Update and delete Employee");
        update_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_employeeActionPerformed(evt);
            }
        });

        employee_payment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employee_payment.setText("Employee Payment");
        employee_payment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employee_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_paymentActionPerformed(evt);
            }
        });

        working_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        working_employee.setText("Working Employees");
        working_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        working_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                working_employeeActionPerformed(evt);
            }
        });

        Leaved_employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leaved_employee.setText("Leaved Employee");
        Leaved_employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Leaved_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leaved_employeeActionPerformed(evt);
            }
        });

        log_out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log_out.setText("Log Out");
        log_out.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("E-mail ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CNIC Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Room Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Month");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Dues / Amount");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Student Fee Form");

        Dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("dd-MMM-yyyy");
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(update_employee)
                                .addGap(363, 363, 363)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(employee_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(working_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Leaved_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(living_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel5)
                                .addGap(74, 74, 74)
                                .addComponent(jTextField4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(New_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)
                                .addGap(151, 151, 151)
                                .addComponent(jTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(manage_room, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(209, 209, 209)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(165, 165, 165)))
                                .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(student_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel4)))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(new_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leaved_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel6)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jScrollPane1)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manage_room, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(New_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(living_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leaved_student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(new_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(employee_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(working_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Leaved_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        Login Li = new Login();
        Li.show();
        this.hide();
    }//GEN-LAST:event_log_outActionPerformed

    private void manage_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_roomActionPerformed
        // TODO add your handling code here:
       new Manage_Room().setVisible(true);
          this.hide();
    }//GEN-LAST:event_manage_roomActionPerformed

    private void New_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_studentActionPerformed
        // TODO add your handling code here:
         new New_Students().setVisible(true);
        
        this.hide();
      
    }//GEN-LAST:event_New_studentActionPerformed

    private void update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studentActionPerformed
        // TODO add your handling code here:
           new Update_and_delete_students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_update_studentActionPerformed

    private void student_feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_feeActionPerformed
        // TODO add your handling code here:
     //    new Student_fee().setVisible(true);
     //   this.hide();
    }//GEN-LAST:event_student_feeActionPerformed

    private void leaved_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaved_studentActionPerformed
        // TODO add your handling code here:
        new Leaved_Students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_leaved_studentActionPerformed

    private void new_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_employeeActionPerformed
        // TODO add your handling code here:
        new New_Employee().setVisible(true);
        this.hide();
    }//GEN-LAST:event_new_employeeActionPerformed

    private void update_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_employeeActionPerformed
        // TODO add your handling code here:
         new Update_and_delete_Employee().setVisible(true);
        this.hide();
    }//GEN-LAST:event_update_employeeActionPerformed

    private void employee_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_paymentActionPerformed
        // TODO add your handling code here:
         new Employee_Payment().setVisible(true);
        this.hide();
    }//GEN-LAST:event_employee_paymentActionPerformed

    private void working_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_working_employeeActionPerformed
        // TODO add your handling code here:
         new Working_Employees().setVisible(true);
        this.hide();
    }//GEN-LAST:event_working_employeeActionPerformed

    private void Leaved_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leaved_employeeActionPerformed
        // TODO add your handling code here:
         new Leaved_Employees().setVisible(true);
        this.hide();
    }//GEN-LAST:event_Leaved_employeeActionPerformed

    private void living_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_living_studentActionPerformed
        // TODO add your handling code here:
        new Living_Students().setVisible(true);
        this.hide();
    }//GEN-LAST:event_living_studentActionPerformed

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
         new Dashboard().setVisible(true);
         this.hide();
    }//GEN-LAST:event_DashboardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String tf = jTextField3.getText();
        if(jTextField3.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(this,"Search field is empty \n Kindly give input");
        }
        else
        {
            try{

            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("Select * from new_Student where ID_No like '%"+tf+"%'");
            ResultSet stu=conn.createStatement().executeQuery("Select * from new_Student where ID_No like '%"+tf+"%' and living='Yes'");
            ResultSet r=conn.createStatement().executeQuery("Select * from fees where ID_No='"+tf+"' order by month DESC");
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            
            if(stu.next())
            {
                if(rs.next())
            {
                String name = rs.getString("name");
                jTextField1.setText(name);
                String email = rs.getString("Email_id");
                jTextField2.setText(email);
                String CNIC = rs.getString("Id_No");
                jTextField3.setText(CNIC);
                String room =rs.getString("Room_No");
                jTextField4.setText(room);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"No data Exists","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jDateChooser2.setDate(null);
               // jDateChooser2.setDate();
            }
            }
            
             else
            {
                JOptionPane.showMessageDialog(this,"This Student is not living in this hostel at this time.","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jDateChooser2.setDate(null);
            }

        }
        catch(Exception e)
        {
            System.out.println("   Error");

        }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String CNIC = jTextField3.getText();
        String amount = jTextField5.getText();
      //  Date month = jDateChooser2.getDate();
    //    int dat;
    //    Calendar cal = Calendar.getInstance();
    //    dat =cal.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        String date = sdf.format(jDateChooser2.getDate());
     //   System.out.println(date);

        SimpleDateFormat sd = new SimpleDateFormat("MMM-yyyy");
        String check_date = sd.format(jDateChooser2.getDate());
        
      //  t1.setDate(date);
       // System.out.println(date);

        try{
            ResultSet r =conn.createStatement().executeQuery("Select * from fees where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
        /*    ResultSet s =conn.createStatement().executeQuery("Select count(*) from fees where ID_No="+CNIC+";");
            String count = s.getString("count(*)");
            for (int i = 0; i < count.length(); i++) {
                String fee_date = r.getString("month");
                System.out.println(fee_date);
            }*/
            if(r.next())
            {
              JOptionPane.showMessageDialog(this,"'"+CNIC+"' already paid his/her fee of this month.","",JOptionPane.PLAIN_MESSAGE);
            }
            else
            {
            conn.createStatement().executeQuery("insert into fees(ID_No, month, amount) values('"+CNIC+"','"+date+"','"+amount+"')");
            JOptionPane.showMessageDialog(this,"Fee Paid Successfully","",JOptionPane.PLAIN_MESSAGE);
            ResultSet rs=conn.createStatement().executeQuery("Select * from fees order by ID_No ASC");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }    
            
        }
        catch(Exception e)
        {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jDateChooser2.setDate(null);
                
                try{
            Statement st=conn.createStatement();
        //    conn.createStatement().executeQuery("delete from fees");
        //    conn.createStatement().executeQuery("delete from new_student");
        //    conn.createStatement().executeQuery("delete from new_employee");
            
            ResultSet rs=st.executeQuery("Select * from fees order by ID_No ASC");
               
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         }  
            catch(Exception e)
                    {
                    System.out.println("   Error");
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         String CNIC = jTextField3.getText();
     
        SimpleDateFormat sdf = new SimpleDateFormat("MMM-yyyy");
        String check_date = sdf.format(jDateChooser2.getDate());
        
      //  t1.setDate(date);
       // System.out.println(date);

        try{
            ResultSet r =conn.createStatement().executeQuery("Select * from fees where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
            
                if(r.next())
            {
             
           int response= JOptionPane.showConfirmDialog(this, "Are you sure You want to delete fee record?", "Confirm",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.YES_OPTION)
            {
                 try{ 
               conn.createStatement().executeQuery("delete from fees where ID_No='"+CNIC+"' and month like '%"+check_date+"'");
               JOptionPane.showMessageDialog(this,"Fee data deleted","",JOptionPane.PLAIN_MESSAGE);
            }
            catch(Exception e)
            {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
            }
            }}
                else
            {
            JOptionPane.showMessageDialog(this,"No data Exists","",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jDateChooser2.setDate(null);
            ResultSet rs=conn.createStatement().executeQuery("Select * from fees order by ID_No ASC");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }    
           
            
            
        }
        catch(Exception e)
        {
            //       JOptionPane.showMessageDialog(this,"Error","",JOptionPane.ERROR_MESSAGE);
            System.out.println("   Error");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_fee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Leaved_employee;
    private javax.swing.JButton New_student;
    private javax.swing.JButton employee_payment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton leaved_student;
    private javax.swing.JButton living_student;
    private javax.swing.JButton log_out;
    private javax.swing.JButton manage_room;
    private javax.swing.JButton new_employee;
    private javax.swing.JButton student_fee;
    private javax.swing.JButton update_employee;
    private javax.swing.JButton update_student;
    private javax.swing.JButton working_employee;
    // End of variables declaration//GEN-END:variables
}
